
ventana:
  monitores: 4
  width: 45
  height: 35

figuras:
  - inicio: 1000
    fin: 2000000
    pos_x_inicio: -5
    pos_y: 2
    pos_x_final: 200
    angulo: 90
    periodo: 200
    figura: |
      | | |x| | |
      | |x|x|x| |
      |x|x|x|x|x|
      | |x|x|x| |
      | |x|x|x| |
