
ventana:
  rows: 200
  columns: 200

figuras:
  - inicio: 1000
    fin: 2000000
    pos_x_inicio: 10
    pos_y: 2
    pos_x_final: 80
    angulo: 90
    periodo: 200
    figura: |
      | | |x| | |
      | |x|x|x| |
      |x|x|x|x|x|
      | |x|x|x| |
      | |x|x|x| |
