ventana:
  rows: 50
  columns: 100

figuras:
  - inicio: 1000
    fin: 9000
    pos_y: 2
    figura: |
      | |x|x|x| |
      |x| | | |x|
      |x| |x| | |
      |x| | | |x|
      | |x|x|x| |
  - inicio: 10000
    fin: 15000
    pos_y: 12
    figura: |
      | |o|o|o| |
      |o| | | |o|
      |o| |o| | |
      |o| | | |o|
      | |o|o|o| |